{
 "title": "harbor-dashbord",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Harbor整体数据", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Harbor空间使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(harbor_system_volumes_bytes{storage=\"free\"}) / sum(harbor_system_volumes_bytes{storage=\"total\"})"
    }
   ]
  },
  {
   "title": "Harbor无状态组件",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sort(sum(kube_deployment_status_replicas_available{namespace=\"harbor-2\"}) by (deployment))"
    }
   ]
  },
  {
   "title": "Harbor Cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total_irate5m{namespace=\"harbor-2\"} > 0",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Harbor有状态组件",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_ready{namespace=\"harbor-2\"}) by (statefulset)"
    }
   ]
  },
  {
   "title": "Harbor网络IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_network_receive_bytes_total_irate5m{namespace=\"harbor-2\"} > 0",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "12小时内镜像拉取排行榜",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(sum(topk(10,increase(harbor_image_pull_count[12h]))) by (repo_name, repo_tag)) > 0"
    }
   ]
  },
  {
   "title": "全体Repo",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sort_desc(sum(harbor_repositories_pull_total) by (repo_name, repo_tag))"
    },
    {
     "expr": "sort_desc(sum(harbor_repositories_push_total) by (repo_name, repo_tag))"
    },
    {
     "expr": "sort_desc(sum(harbor_repositories_tags_total) by (repo_name, repo_tag))"
    }
   ]
  },
  {
   "title": "Harbor 内存使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"harbor-2\"} > 0",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "container_spec_memory_limit_bytes{namespace=\"harbor-2\"} > 0",
     "legendFormat": "{{pod_name}}-limit"
    }
   ]
  }
 ]
}